# Generated by Django 2.2.1 on 2019-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_auto_20190525_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
