# Generated by Django 2.2.1 on 2019-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpenter',
            name='dist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
