# Generated by Django 2.2.1 on 2019-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_auto_20190529_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('dist', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['dist'],
            },
        ),
        migrations.CreateModel(
            name='Mason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('dist', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['dist'],
            },
        ),
        migrations.DeleteModel(
            name='Maid',
        ),
        migrations.AlterModelOptions(
            name='plumber',
            options={'ordering': ['dist']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='Services',
        ),
        migrations.AddField(
            model_name='plumber',
            name='dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plumber',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plumber',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
