# Generated by Django 2.2.1 on 2019-07-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_cleaner_cook_electrician_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpenter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='person'),
        ),
    ]
