# Generated by Django 2.2.1 on 2019-07-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_auto_20190724_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpenter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
